/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.16                          *
*        Compiled Jun  4 2012, 15:48:59                              *
*        (c) 2011 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "FramewinDLG.h"
#include "PROGBAR.h"
#include "glcd.h"
#include <stdio.h>
#include "WM.h"
#include "bsp_tft_lcd.h"
#include "main.h"
#include "SimSun_16.h"
#include "BUTTON.h"
#include "GUI_task.h"
#include "ucOS_Task.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/



// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*PROGBAR_CreateIndirect
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "TEST", ID_FRAMEWIN_0, 300, 160, 200, 160 },
  { TEXT_CreateIndirect, "Begin test?", ID_TEXT_0, 60, 20, 80, 40 },
  { BUTTON_CreateIndirect, "COFIRM", ID_BUTTON_0, 30, 80, 55, 55 },
  { BUTTON_CreateIndirect, "CANCEL", ID_BUTTON_6, 115, 80, 55, 55 },
  // USER START (Optionally insert additional widgets)
  // USER END
};
/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int Id, NCode;
  WM_HWIN hDlg_Qc;
	FONT_T tFont;			/* 定义一个字体结构体变量，用于设置字体参数 */
  hDlg_Qc = pMsg->hWin;
	
	
	{
		tFont.usFontCode = FC_ST_16;	/* 字体代码 16点阵 */ // 汉字大小为16*16 字母大小为 宽8高16
		tFont.usTextColor = CL_BLACK;	/* 字体颜色 */
		tFont.usBackColor = CL_WHITE;	/* 文字背景颜色 */
		tFont.usSpace = 0;				/* 文字间距，单位 = 像素 */
	}
	
	hItem = WM_GetDialogItem(hDlg_Qc, ID_BUTTON_0);
  //BUTTON_SetFont(hItem,&GUI_FontHZ_SimSun_24);
	hItem = WM_GetDialogItem(hDlg_Qc, ID_BUTTON_6);
  //BUTTON_SetFont(hItem,&GUI_FontHZ_SimSun_24);
//   BUTTON_SetTextColor(hItem,0,GUI_CYAN);
//   BUTTON_SetBkColor(hItem,0,GUI_BLUE);
	
	//BUTTON_SetSkin(hItem, BUTTON_SKIN_FLEX);
	
  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Framewin'
    //
    hItem = pMsg->hWin;
    FRAMEWIN_SetFont(hItem, &GUI_Font8x15B_ASCII);
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
	  switch(NCode) 
	  {
			case WM_NOTIFICATION_RELEASED:      /* React only if released */
				switch(Id) 
				{
					case ID_BUTTON_0: 
					{
						GUI_EndDialog(hDlg_Qc,0);
						break;
					}
					case ID_BUTTON_6: // Notifications sent by 'Edit'
					{
						break;
					}
			 }
			 break;
	  }
    break;
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       CreateFramewin
*/

WM_HWIN CreateFramewin(void) {
  WM_HWIN hWin;
  WM_SetCreateFlags(WM_CF_MEMDEV);
  hWin = GUI_ExecDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), &_cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}



/*************************** End of file ****************************/
